# GitHub defaults that cannot be overridden
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false

# GitHub defaults that can be changed
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate

# Site settings
title: Mike Camilleri
url: "https://mikecamilleri.com"

# Build settings
timezone: US/Pacific
exclude: ["Gemfile", "Gemfile.lock", "README.md", "CNAME"]

gems:
  - jekyll-redirect-from

permalink: "/blog/:title/"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
