# GitHub defaults that can be overridden
# here for reference
# highlighter: pygments
# github: [Repository metadata]
# # https://help.github.com/articles/repository-metadata-on-github-pages/

# GitHub defaults that can not be overridden
# here for use while running locally
# safe: true
lsi: false
# source: your top-level directory

# MY SETTINGS

# Site settings
title: Mike Camilleri
url: "http://mikecamilleri.com"

# Build settings
timezone: US/Pacific
exclude: ["Gemfile", "Gemfile.lock", "README.md", "CNAME"]

markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter: pygments

gems:
  - jekyll-redirect-from

permalink: "/blog/:title/"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
