# GitHub defaults that cannot be overridden
lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# GitHub defaults that can be changed
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate

# Site settings
title: Mike Camilleri
url: "https://mikecamilleri.com"

# Build settings
markdown: GFM
timezone: America/New_York
exclude: ["Gemfile", "Gemfile.lock", "README.md", "CNAME"]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/blog/:title/"
